### ISSUE TITLE
Terraform file"${file("user-data.sh")}" doesn't work

### ISSUE THREAD

**Issue by talfik2** [serverscom/terraform-provider-serverscom#11]
Hello,
I am trying to configure my user-data as it is explained in https://registry.terraform.io/providers/serverscom/serverscom/latest/docs/guides/user-data. My user-data basically installs the docker in an ec2 instance that I configured via Terraform. Whenever I apply the changes, user-data just doesn't work, and docker is not installed as a result.
- My user-data is in the same location with `main.tf`
- Name of my user-data is `entry-script.sh`. My user-data is:
```bash
#! /bin/bash

yum update -y
amazon-linux-extras install docker -y
systemctl start docker
systemctl enable docker
usermod -a -G docker ec2-user
``` 

- Instance resource is:

```terraform
resource "aws_instance" "projede-olusturulan-instance" {
    ami = data.aws_ami.latest-amazon-linux-image.id
    instance_type = var.instance_type

    subnet_id = aws_subnet.proje-subnet-1.id
    availability_zone = var.avail_zone

    associate_public_ip_address = true
    key_name = var.keypem

    user_data = "${file("entry-script.sh")}"

    tags = {
        Name: "${var.env_prefix}-server"
    }
}
```

**Comment by kzaitsev** [comment]
Hi, this guide is for the servers.com provider, not aws. We can't help you with your issue. You can try to contact with aws support to solve your issue.

**Comment by talfik2** [comment]
> 

This guide is from Terraform's documentation, if you are not going to solve the documents regarding to the documentation, you should better contact AWS and let them be the provider of the @Terraform documentation.

**Comment by kzaitsev** [comment]
@talfik2 sorry, but let me explain to You.

This is not a part of terraform documentation. This is a part of servers.com terraform provider documentation. Each provider has its documentation published on terraform registry on which link you provided in the issue.

Servers.com and Amazon are two different hosting providers with their own terraform providers. This repository and documentation are maintained by Servers.com Inc employees, not Terraform, and not Amazon.
